version: "3.8"

services:
  web:
    build: .
    env_file:
      - ./.env.local
    container_name: sync
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src:rw
    restart: always
